default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: password1
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: fantasy_rankings_development

test:
  <<: *default
  database: fantasy_rankings_test
