# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3005dfcc1f6157a3c59688e58f46d231812b9cc616e03d212da7cd01ccabde56db56f5a50c5a3f28fbd9d69486f1f784bbcab8270144d186feca33739bd0e38

test:
  secret_key_base: 8cb71dbc70031de63541dea528369f4fdd3e0f130a582e2a0b8891839b9594aae23efd6e82ff24522a49293e0cbf207de293aacad99229638cc1605d078eae93

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
